version: '3.8'

services:
  structurizr:
    build:
        context: .
        dockerfile: Structurizr.Dockerfile
    image: structurizr-lite:lastest
    volumes:
        - ./structurizr:/usr/local/structurizr
    ports:
        - "8080:8080"
    # environment:
      # WORDPRESS_DB_HOST: host.docker.internal
